import { Client, GatewayIntentBits } from "discord.js";
import "dotenv/config";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { striveCharacters } from "../game-data/characters.js";

const client = new Client({ intents: [GatewayIntentBits.Guilds] });
await client.login(process.env.DISCORD_TOKEN);

const assetDir = path.join(import.meta.dirname, "../../assets/emoji");
const existing = await client.application!.emojis.fetch();
const mapping: Record<string, { id: string; name: string }> = {};

for (const char of striveCharacters) {
  const filePath = path.join(assetDir, `${char.id}.png`);

  try {
    await readFile(filePath);
  } catch {
    console.warn(`no image found for ${char.name}, skipping`);
    continue;
  }

  const already = existing.find((e) => e.name === char.id);
  if (already) {
    mapping[char.id] = { id: already.id, name: already.name };
    console.log(`emoji for ${char.name} already existed`);
    continue;
  }

  const buffer = await readFile(filePath);
  const created = await client.application!.emojis.create({ attachment: buffer, name: char.id });
  mapping[char.id] = { id: created.id, name: created.name };
  console.log(`uploaded ${char.name}`);
}
const outPath = path.join(import.meta.dirname, "../game-data/generated-emoji.ts");
const content = `// AUTO-GENERATED by lib/upload-emoji.ts, do not edit by hand
export const characterEmoji: Record<string, { id: string, name: string }> = ${JSON.stringify(mapping, null, 2)};
`;
await writeFile(outPath, content);

console.log(`wrote ${Object.keys(mapping).length} emoji to game-data/generated-emoji.ts`);
process.exit(0);
