export const CHARACTER_SEED = [
  { id: "SO", name: "Sol" },
  { id: "KY", name: "Ky" },
  { id: "MA", name: "May" },
  { id: "AX", name: "Axl" },
  { id: "CH", name: "Chipp" },
  { id: "PO", name: "Potemkin" },
  { id: "FA", name: "Faust" },
  { id: "MI", name: "Millia" },
  { id: "ZA", name: "Zato-1" },
  { id: "RA", name: "Ramlethal" },
  { id: "LE", name: "Leo" },
  { id: "NA", name: "Nagoriyuki" },
  { id: "GI", name: "Giovanna" },
  { id: "AN", name: "Anji" },
  { id: "IN", name: "I-No" },
  { id: "GO", name: "Goldlewis" },
  { id: "JC", name: "Jack-O'" },
  { id: "HA", name: "Happy Chaos" },
  { id: "BA", name: "Baiken" },
  { id: "TE", name: "Testament" },
  { id: "BI", name: "Bridget" },
  { id: "SI", name: "Sin" },
  { id: "BE", name: "Bedman?" },
  { id: "AS", name: "Asuka" },
  { id: "JN", name: "Johnny" },
  { id: "EL", name: "Elphelt" },
  { id: "AB", name: "A.B.A." },
  { id: "SL", name: "Slayer" },
  { id: "DI", name: "Dizzy" },
  { id: "VE", name: "Venom" },
  { id: "UN", name: "Unika" },
  { id: "LU", name: "Lucy" },
  { id: "JA", name: "Jam" },
  { id: "RK", name: "Robo-Ky" },
];
